import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { GlobalProvider } from "./components/context/GlobalContext";
import AnnouncementBar from "./components/user/AnnouncementBar";
import Navbar from "./components/user/Navbar";
import Footer from "./components/user/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <GlobalProvider>
            <AnnouncementBar />
                <Navbar/>
        {children}

              <Footer />
        </GlobalProvider>
      </body>
    </html>
  );
}
