import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { GlobalProvider } from "../components/context/GlobalContext";
import AnnouncementBar from "../components/user/AnnouncementBar";
import Navbar from "../components/user/Navbar";
import Footer from "../components/user/Footer";
import CartSidebar from "../components/user/CartSidebar";
import LoginSignup from "../components/user/LoginSignup";
import Wishlist from '../components/user/Wishlist'
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import OrderSidebar from '../components/user/OrderSidebar'
import Icon from "../components/user/Icons";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        // style={{ backgroundImage: "url('/Images/homeBG.webp')" }}
        className={`${geistSans.variable} ${geistMono.variable} antialiased  `}
      >
        <GlobalProvider>
            <AnnouncementBar />
                <Navbar/>
                      <CartSidebar/>
                      <LoginSignup/>
                      <Wishlist/>
                      <OrderSidebar/>
                
        {children}
<Icon/>
              <Footer />
        </GlobalProvider>
        <ToastContainer position="top-right" autoClose={3000} hideProgressBar />
      </body>
    </html>
  );
}
